USE papertrail;

SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE ActivityLog;
TRUNCATE TABLE Revision;
TRUNCATE TABLE PaperGrant;
TRUNCATE TABLE PaperTopic;
TRUNCATE TABLE Authorship;
TRUNCATE TABLE Paper;
TRUNCATE TABLE `Grant`;
TRUNCATE TABLE Topic;
TRUNCATE TABLE Venue;
TRUNCATE TABLE User;
TRUNCATE TABLE Role;

SET FOREIGN_KEY_CHECKS = 1;
